# Generated by Django 5.0.6 on 2024-07-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nib', '0005_login_token_remove_nimbo_users_login_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nimbo_users',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
