# Generated by Django 5.0.6 on 2024-07-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nib', '0007_delete_login_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagonsis',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
