# Generated by Django 5.0.6 on 2024-07-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nib', '0010_alter_user_diagonsis_user_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_diagonsis',
            old_name='diagonsis_id',
            new_name='diagnosis_id',
        ),
    ]
