# Generated by Django 5.0.6 on 2024-07-18 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nib', '0011_rename_diagonsis_id_user_diagonsis_diagnosis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_diagonsis',
            name='diagnosis_id',
        ),
        migrations.AddField(
            model_name='user_diagonsis',
            name='diagnosis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nib.diagonsis'),
            preserve_default=False,
        ),
    ]
