# Generated by Django 5.0.6 on 2024-07-18 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nib', '0012_remove_user_diagonsis_diagnosis_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_symptoms',
            name='symptoms_id',
        ),
        migrations.AddField(
            model_name='user_symptoms',
            name='symptoms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nib.symptoms'),
            preserve_default=False,
        ),
    ]
