# Generated by Django 5.0.6 on 2024-07-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nib', '0014_post_feed_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_type',
            new_name='media_type',
        ),
    ]
