# Generated by Django 5.0.6 on 2024-07-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimbouser', '0003_nimbo_users_otp_verify_delete_nimbouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nimbo_users',
            name='user_token',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
