# Generated by Django 5.0.6 on 2024-07-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nimbouser', '0004_alter_nimbo_users_user_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nimbo_users',
        ),
        migrations.DeleteModel(
            name='otp_verify',
        ),
    ]
