# Generated by Django 5.0.6 on 2024-07-11 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_goals', '0003_delete_add_user_delete_diagonsis_delete_healthstyle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='health_goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=150)),
                ('login_token', models.CharField(max_length=150)),
                ('goal_id', models.IntegerField()),
                ('soft_delete', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='HealthGoal',
        ),
    ]
