# Generated by Django 5.0.6 on 2024-07-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_goals', '0004_health_goal_delete_healthgoal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='health_goal',
        ),
    ]
