# Generated by Django 5.0.6 on 2024-07-08 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('d_o_b', models.DateField(default=django.utils.timezone.now)),
                ('nick_name', models.CharField(max_length=150)),
                ('image_url', models.URLField()),
                ('soft_delete', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
