# Generated by Django 5.0.6 on 2024-07-10 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_goals', '0002_healthgoal_login_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_user',
        ),
        migrations.DeleteModel(
            name='Diagonsis',
        ),
        migrations.DeleteModel(
            name='HealthStyle',
        ),
        migrations.DeleteModel(
            name='NimboUser',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Symptoms',
        ),
        migrations.AlterModelOptions(
            name='healthgoal',
            options={'verbose_name': 'Health Goal', 'verbose_name_plural': 'Health Goals'},
        ),
        migrations.AlterField(
            model_name='healthgoal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='healthgoal',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At'),
        ),
    ]
