# Generated by Django 5.0.6 on 2024-07-11 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('soft_delete', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='diagonsis',
            name='login_token',
        ),
        migrations.RemoveField(
            model_name='health_goal',
            name='login_token',
        ),
    ]
