# Generated by Django 5.0.6 on 2024-07-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nib', '0003_feed_post_health_style_user_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_goal',
            name='user_token',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
