# Generated by Django 5.0.6 on 2024-07-13 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nib', '0004_alter_health_goal_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(max_length=150)),
                ('login_token', models.CharField(max_length=150)),
                ('device_details', models.JSONField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='nimbo_users',
            name='login_token',
        ),
        migrations.AddField(
            model_name='diagonsis',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='diagonsis',
            name='icon',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nimbo_users',
            name='firebase_json',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='icon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='diagonsis',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diagonsis',
            name='user_token',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='nimbo_users',
            name='d_o_b',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nimbo_users',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='nimbo_users',
            name='nick_name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nimbo_users',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='user_token',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user_symptoms_diagonsis',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user_symptoms_diagonsis',
            name='user_token',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
