# Generated by Django 5.0.6 on 2024-07-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nib', '0006_alter_nimbo_users_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_token',
        ),
    ]
