# Generated by Django 5.0.6 on 2024-07-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nib', '0009_user_diagonsis_user_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_diagonsis',
            name='user_token',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user_symptoms',
            name='user_token',
            field=models.CharField(max_length=150),
        ),
    ]
