# Generated by Django 5.0.6 on 2024-07-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nib', '0015_rename_post_type_post_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='private_post',
            field=models.BooleanField(default=False),
        ),
    ]
