# Generated by Django 5.0.6 on 2024-07-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nib', '0016_alter_post_private_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_urls',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
