# Generated by Django 5.0.6 on 2024-07-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_diagnosis', '0002_diagonsis_login_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagonsis',
        ),
    ]
