# Generated by Django 5.0.6 on 2024-07-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagonsis',
            name='login_token',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
